site_name: My Documentation
site_description: Comprehensive guides and documentation
site_author: Mohammed Althaf

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo

nav:
  - Home: index.md
  - WindowsSocureFiles:
      - Overview: WindowsSocureFiles/index.md
      - Usage: WindowsSocureFiles/usage.md
  - Project-Beta:
      - Overview: project-beta/index.md
      - Usage: project-beta/usage.md

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: true
